In [1]:
import numpy as np

In [2]:
l1st2=np.array([1,2,3,4,5,])
sacle=6
add=l1st2+sacle
add

array([ 7,  8,  9, 10, 11])

In [3]:
a=np.array([10,20,30,40])
a[1:3]

array([20, 30])

In [4]:
a[:]

array([10, 20, 30, 40])

In [5]:
np.random.rand(3,3)

array([[0.09896209, 0.23722286, 0.0584315 ],
       [0.014228  , 0.50128145, 0.11061135],
       [0.32859168, 0.44029152, 0.72027091]])

In [6]:
np.random.randint(0,100,10)

array([50, 53, 14, 87, 23, 15, 86, 83, 58, 72])

In [7]:
arr=np.array([10,50,75,8])
arr.reshape(2,2)


array([[10, 50],
       [75,  8]])

In [8]:
arr.max()

75

In [9]:
arr.min()

8

In [10]:
arr.argmax()

2

In [11]:
arr.argmin()

3

In [12]:
arrr=np.where(arr>25)
arr[arrr]

array([50, 75])

In [13]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arrrr=arr[0:5]
arrrr

array([0, 1, 2, 3, 4])

In [15]:
arrrr[:]= 100
arrrr

array([100, 100, 100, 100, 100])

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [81]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(mat[1::,:2:])

[[4 5]
 [7 8]]
