## numby


In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]
type(my_list)

list

In [ ]:
arr = np.array(my_list)
type(arr)

numpy.ndarray

In [ ]:
my_matrix = [[1,2,3],[1,2,3]]
my_matrix=np.array(my_matrix)
my_matrix

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
my_matrix.shape

(2, 3)

In [ ]:
# listt = [1,2,3,4,5]
# sacle = 6
# add= listt + sacle
# add

In [ ]:
listt = np.array([1,2,3,4,5])
sacle = 6
add= listt + sacle
add

array([ 7,  8,  9, 10, 11])

In [ ]:
list1=[1,2,3]
additional= list1 + list1
additional

[1, 2, 3, 1, 2, 3]

In [ ]:
list1 = np.array([1,2,3])
list2 = np.array([1,2,3])
addi = list1 + list2
addi

array([2, 4, 6])

In [ ]:
a = np.array([[1,2] , [3,4]])
b = np.array([[1,2] , [1,2]])
c = a + b
c

array([[2, 4],
       [4, 6]])

In [ ]:
z= a*b    #elementwise
z

array([[1, 4],
       [3, 8]])

In [ ]:
a.dot(b)   # dot product

array([[ 3,  6],
       [ 7, 14]])

In [ ]:
a.T

array([[1, 3],
       [2, 4]])

In [ ]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
res = np.add(a , b) #  or a + b
res

array([ 3,  7, 11, 15])

In [ ]:
res = np.subtract(a , b) #  or a - b
res

array([1, 1, 1, 1])

In [ ]:
res = np.divide(a , b) #  or a / b
res

array([2.        , 1.33333333, 1.2       , 1.14285714])

In [ ]:
res = np.multiply(a , b) #  or a * b
res

array([ 2, 12, 30, 56])

In [ ]:
res = np.power(b, 2) # or b ** 2
res

array([ 1,  9, 25, 49])

In [ ]:
x = [25, 9, 36]
res = np.sqrt(x)
res

array([5., 3., 6.])

In [ ]:
a = np.array([10, 20, 30, 40])

In [ ]:
a[1]

np.int64(20)

In [ ]:
a[1:3] # access more than one sequential item using slicing

array([20, 30])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.full((2,2),7) # constant array
a

array([[7, 7],
       [7, 7]])

In [ ]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(0,10) # numbers from 0 to 10-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2) # numbers from 0 to 10-1 in step = 2

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,10,3) # first number = 0 --- last number=10 and i need 3 numbers

array([ 0.,  5., 10.])

In [ ]:
np.random.rand(2) # any 2 floats random numbers

array([0.82771695, 0.56417667])

In [ ]:
np.random.rand(3,3) # matrix (3,3) of any numbers

array([[0.57736623, 0.13082028, 0.05755884],
       [0.92455298, 0.43015516, 0.76748887],
       [0.74827853, 0.72114226, 0.42611314]])

In [ ]:
np.random.randint(0 , 11 , (2,2)) # random int numbers --- low_number = 0  --- high_number = 10 --- matrix = (2,2)

array([[2, 9],
       [0, 7]])

In [ ]:
np.random.randint(0 , 100 ,10) # need 10 random int numbers

array([45, 37, 10, 16, 13, 53, 20, 64, 92, 34])

In [ ]:
np.random.randn(2)

array([ 0.97262229, -0.40346748])

In [ ]:
arra = np.arange(25)
arra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arra.reshape(5,5) # convert the array to matrix with the same numbers of the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr = np.array([10,50,75,8])
arr

array([10, 50, 75,  8])

In [ ]:
arr.max() #max number in the array

np.int64(75)

In [ ]:
arr.min() #min number in the array

np.int64(8)

In [ ]:
arr.argmax() # return the index of the max number

np.int64(2)

In [ ]:
arr.reshape(2,2)

array([[10, 50],
       [75,  8]])

In [ ]:
arr.argmax() # the matrix become an array and return the index

np.int64(2)

In [ ]:
where_no = np.where(arr > 25)
arr[where_no]

array([50, 75])

In [ ]:
result = np.where(arr % 2 == 0, 'even', 'odd')
print(result)

['even' 'even' 'odd' 'even']


In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_arr = arr[0:5]
new_arr

array([0, 1, 2, 3, 4])

In [ ]:
new_arr[:] = 100
new_arr

array([100, 100, 100, 100, 100])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
import copy
original = [1,2,[3,4]]
shallow_copy = copy.copy(original)
shallow_copy[2][0] = 99
print(original)
print(shallow_copy)

[1, 2, [99, 4]]
[1, 2, [99, 4]]


In [ ]:
import copy
original = [1,2,[3,4]]
deep_copy = copy.deepcopy(original)
deep_copy[2][0] = 99
print(original)
print(shallow_copy)

[1, 2, [3, 4]]
[1, 2, [99, 4]]


In [ ]:
matrix  = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])          # [    :    ,    :   ]
                                      #    rows     columns
matrix[1:3, 0:2]

array([[4, 5],
       [7, 8]])